### ISSUE TITLE
How to download the current version

### ISSUE THREAD

**Issue by StefanMaron** [hougaard/BCCL_support#16]
I got the educational version some time ago, and want to download the current version, but I can not find any download link on https://www.hougaard.com/bccl/

**Comment by hougaard** [comment]
Can you log into your order and download from there?

**Comment by StefanMaron** [comment]
How do I access my order? I can not find any mail from order and on the website I can not find any login area :/

**Comment by hougaard** [comment]
I have sent you a link in an email.
