### ISSUE TITLE
Table view does not filter on Export

### ISSUE THREAD

**Issue by StefanMaron** [hougaard/BCCL_support#17]
**Describe the bug**
The table view setting does not filter the results on export.

**To Reproduce**
![image](https://user-images.githubusercontent.com/24838311/103507496-9d215880-4e5f-11eb-8670-104d384518d6.png)
![image](https://user-images.githubusercontent.com/24838311/103507587-d3f76e80-4e5f-11eb-9247-1f67f9461534.png)

**Expected behavior**
The table view setting should filter the results on export.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: BCCL_1.15.0.113

**Comment by hougaard** [comment]
Please try with No. instead of Nr.... or try with using Field1

**Comment by StefanMaron** [comment]
Okay, with this command `BCCL -t getdata -s table=18 "view=SORTING(No.) WHERE(No.=FILTER(100000))" -o "test.csv" -f csv -l ;` it works. So this is probably a localization error of the command builder.

According to docs https://docs.microsoft.com/en-us/dynamics-nav/getview-function--filterpagebuilder-#parameters the filterpagebuilder can return field names, but field captions is the default.

**Comment by hougaard** [comment]
Got it, grab build 114 in on hours time  (you know the URL).
