### ISSUE TITLE
BCCL with windows authentication

### ISSUE THREAD

**Issue by StefanMaron** [hougaard/BCCL_support#18]
**Describe the bug**
When trying to authenticate bccl to a bc instance with windows auth, I always get a 401 error.
Not sure if this is supported or not?

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 1.15.0.114

**Comment by hougaard** [comment]
Currently not supported. Honestly, we have not had many requests for that. We never use Windows authentication anywhere with BC, because, you know, cloud :)

I'll test it, thanks!

**Comment by hougaard** [comment]
Hmm... just installed a docker container running Windows authentication.

Verified in a browser that I indeed got the "windows authentication" login dialog apposed to the basic auth dialog.

BCCL worked fine:
```
C:\projects\bccl\build\test>BCCL -w "http://bcwindows:7047/BC/WS/CRONUS International Ltd./Codeunit/bccl" -u BCWINDOWS\ERIK -p secretpassword -t tasks
{
  "Tasks": [
    {
      "Task": "DELETEALL",
      "Description": "Delete ALL Data from a table",
      "Codeunit": 80814,
      "Parameters": [
        "table",
        "view",
        "validate"
      ]
    },
    {
      "Task": "DELETEDATA",
      "Description": "Delete Data from a table",
      "Codeunit": 80811,
      "Parameters": [
        "table"
      ]
```

**Comment by StefanMaron** [comment]
hmm, I just created a new container but I still can not login.

Here my docker setup:
```
$containername = 'Test-dev'
$artifactUrl = Get-BCArtifactUrl -version 17.1 -select Latest -country de -type OnPrem

New-NavContainer -accept_eula:$accept_eula `
    -containername $containername `
    -auth Windows `
    -artifactUrl $artifactUrl `
    -updateHosts `
    -shortcuts DesktopFolder `
    -additionalParameters $additionalParameters `
    -memoryLimit 8G `
    -accept_outdated `
    -doNotCheckHealth `
    -doNotExportObjectsToText `
    -useBestContainerOS `
    -DeveloperServicesPort 7049 `
    -imagename myown `
    -enableTaskScheduler `
    -licenseFile "C:\GIT\BC17DEV.flf" 
```
![image](https://user-images.githubusercontent.com/24838311/104415481-62f83b00-5572-11eb-87ed-c6d723f6bb6b.png)

Not sure what the problem is here. 
Are there logs which would be of any help?

**Comment by hougaard** [comment]
Quotes around the user name perhaps? Wonder if the dash in your domain is messing up the parameter. Try adding the --verbose parameter...

**Comment by hougaard** [comment]
here my script, also using the -credential parameter....
```
$containerName = 'bcwindows'
$credential = Get-Credential -Message 'Using Windows authentication. Please enter your Windows credentials for the host computer.'
$auth = 'Windows'
$artifactUrl = Get-BcArtifactUrl -type 'OnPrem' -country 'w1' -select 'Latest'
$licenseFile = 'c:\navision\bc17.flf'
New-BcContainer `
    -accept_eula `
    -containerName $containerName `
    -credential $credential `
    -auth $auth `
    -artifactUrl $artifactUrl `
    -licenseFile $licenseFile `
    -updateHosts
```

**Comment by StefanMaron** [comment]
Does not help, I will try the latest version later and also to specify the credentials like you did

**Comment by hougaard** [comment]
What's your AD server?

**Comment by StefanMaron** [comment]
Not sure if I understand the question. I am currently on my work laptop, I think we have a azure AD

**Comment by hougaard** [comment]
And you're work laptop is part of your work AD? (Not Azure AD)

**Comment by StefanMaron** [comment]
yes, the laptop is in my work AD

**Comment by hougaard** [comment]
Can you access the WS URL from a browser?

**Comment by StefanMaron** [comment]
Yes this works without asking me again for credentials:
![image](https://user-images.githubusercontent.com/24838311/104420125-b28e3500-5579-11eb-8916-14248b9f538f.png)

**Comment by hougaard** [comment]
... but that's not with the "test-dev\stefan_" identity then? That's with your userid from your host machine....

**Comment by StefanMaron** [comment]
but that is because I can not add the work domain to the docker container. Test-dev is the container name.
![image](https://user-images.githubusercontent.com/24838311/104420658-82936180-557a-11eb-8f30-6e74082922f8.png)

**Comment by hougaard** [comment]
I think, without the -credential option, your Windows SIDs are getting mixed up... having the to unconnected AD domains (your host, and the container) doing strange things.

I'm heading to bed now :)
