### ISSUE TITLE
Authentication timeout issues

### ISSUE THREAD

**Issue by bignadad** [hougaard/BCCL_support#20]
**Describe the bug**
I am running putdata commands on xlsx files to upload 200k records to cloud BC. I have uploaded about 75k so far but I keep running into credential errors.
The data will upload at about 12k records every 20 minutes. I seems to do them in 12k~ chunks. 
After about 24k records ill get a message saying credentials are invalid. and it stops.
That example was with the OAuth type.

I tried S2S type and it didn't even make it to the first batch and gave me bad credentials.

Just to be clear when i use these commands
BCCL --auth OAuth
BCCL --auth S2S (with clientid, client secret, and tenant id)
It will connect and say "Access to Business Central authenticated".

So the initial connection is fine. It just doesn't last.

**To Reproduce**
Described above....

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 11

**Comment by hougaard** [comment]
S2S is the answer, have you set that up correctly?

**Comment by bignadad** [comment]
I did it based on your video but can try again and share screenshots.
I have a question first.
When I get an error like this do I need to wait until the process finishes? Or can I just close and fix the issue in the excel file?
It using 15% CPU in taskman so it still processing. I just didn't know if it would skip that record or what.

![image](https://user-images.githubusercontent.com/1048928/211357613-71962aa4-6566-43ae-add1-22484702ba89.png)

**Comment by bignadad** [comment]
Sorry but I'm just trying to understand what's happening. 
Based on the last message I just posted, it said it inserted 12,195
I searched the customer for row 75176 and it's not showing up.

**Comment by bignadad** [comment]
okay. so back to the auth issue
Here is how i have it setup

BCCL -w "https://api.businesscentral.dynamics.com/v2.0/****/Production/WS/****/Codeunit/bccl" --remember
BCCL --auth S2S --clientid ********** --clientsecret "********" --tenantid *****

Then i run my command.
Do i have to remember my auth? It doesn't seem to let me

Here is my application in Azure
![image](https://user-images.githubusercontent.com/1048928/211361590-aff7f29a-6d74-4292-bc28-5e445671d2d5.png)
![image](https://user-images.githubusercontent.com/1048928/211361237-45c23eb2-8b2c-4ed1-b80a-82b7e5e424fb.png)

**Comment by bignadad** [comment]
sorry for all the posts.... The issue was actually adding the azure application to BC. That fixed it.

I do want to clarify something.

Every time i bring up command prompt i need to run the BCCL --auth S2S auth command?
Will that last the entire time i have command prompt open?

**Comment by hougaard** [comment]
No, you should basically add the BCCL --auth S2S ... command before anything else.

Both OAuth and S2S will last for 3600 seconds unless your have changed authentication settings in Azure.

**Comment by curateideas** [comment]
> Both OAuth and S2S will last for 3600 seconds unless you have changed authentication settings in Azure.

Where can this setting be changed? Are there alternatives to cop with the limitation of 3600 seconds, when import needs more time?

**Comment by hougaard** [comment]
What version of BCCL are you running? This should not happen on the latest version. (https://www.hougaard.com/download/)

**Comment by curateideas** [comment]
We're using .179. Just downloaded the newest version and started another test.

**Comment by hougaard** [comment]
Please try, we had some trouble with s2s suddenly using the standard OAuth, but it should be fixed.

**Comment by hougaard** [comment]
Crap, can you run it again, with the --verbose parameter and send all the output to support@hougaard.com ?

**Comment by curateideas** [comment]
It's currently running with --verbose since more than 1,5 hours. I'll wait until it's finished. Will the error message be in the output if running with --verbose?

**Comment by curateideas** [comment]
I can see it now. Error message is included.
