### ISSUE TITLE
Import of undefined Date Fields

### ISSUE THREAD

**Issue by TobiasReineckeCTM** [hougaard/BCCL_support#21]
Describe the bug:
In an export from Dynamics NAV to csv undefined date fields are exported as 01.01.1753.
These values produce an error while importing with BCCL.
The error message is "An error has occurred: Cannot write the value 01/01/1753 to the field Disposal Date in the table Temp. FA Depr. Book CSMPte because the value is either too long or the content is invalid."

To Reproduce:
Run an import into a date field with a file value 01.01.1753

Expected behavior:
Import of date value 01.01.1753 as an undefined date value in BC

Desktop:
 - OS: Windows
 - Version 1.16.0.176

**Comment by hougaard** [comment]
Please update the BCCL app to 1.0.0.179 and try again...

**Comment by TobiasReineckeCTM** [comment]
Perfect 👍 
it works with this version, the undefined date fields are imported correctly
