### ISSUE TITLE
Handle international date-, time- and number format

### ISSUE THREAD

**Issue by cahan0506** [hougaard/BCCL_support#3]
See
https://en.wikipedia.org/wiki/Category:Date_and_time_representation_by_country
https://en.wikipedia.org/wiki/Decimal_separator

Or just possible to specify format in Nav/BC-format or something like Excel-format.
https://support.microsoft.com/en-us/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68

If BCCL should work cross-platform (Linux, Mac, Windows) you might consider a configuration of line breaks as well.
https://stackoverflow.com/questions/3720612/what-is-the-universal-newline-for-all-operating-systems-lf-and-cr

Unless line breaks already are handled by your cross-platform compiler.

**Comment by hougaard** [comment]
Line breaks should work fine across all platforms. We'll take a look at adding a CSV international setting.

Thanks for the report.

**Comment by efoqusca** [comment]
LanguageId to CultureInfo List:
https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a

**Comment by hougaard** [comment]
LanguageId to cultureinfo name
https://docs.microsoft.com/en-us/openspecs/office_standards/ms-oe376/6c085406-a698-4e12-9d4d-c3b0ee3dbc4a

**Comment by hougaard** [comment]
https://docs.microsoft.com/en-us/dotnet/standard/base-types/standard-numeric-format-strings

**Comment by hougaard** [comment]
Supported in build 92
https://www.hougaard.com/bccl-data-formatting-for-csv-files/
