### ISSUE TITLE
Field Caption seems to be wrong on page 80802

### ISSUE THREAD

**Issue by StefanMaron** [hougaard/BCCL_support#5]
**Describe the bug**
Field Caption seems to be wrong on page 80802

**Expected behavior**
I think the caption should be "Create related sub records"

**Screenshots**
![image](https://user-images.githubusercontent.com/24838311/98782139-c1306280-23f7-11eb-94b0-0e6492cf9236.png)

**Comment by hougaard** [comment]
Good catch, will be fixed in next release.
